/**
 * @file AsyncComponentLoading.js
 */

export const ASYNC_COMPONENT_LOADING_START = '@@VIVY/ASYNC_COMPONENT_LOADING_START';
export const ASYNC_COMPONENT_LOADING_COMPLETE = '@@VIVY/ASYNC_COMPONENT_LOADING_COMPLETE';
